apiVersion: v1
kind: Secret
metadata:
    name: ssl-root
    namespace: dev-tools
type: Opaque
stringData:
    tls.crt: ENC[AES256_GCM,data:SsxnUodauuGk7+7W6ZEvhDHZaRchU33X659643Y+y6EWsJFt9jlwfR7MjphFLugnkS7/PnWASmINtePh0z7YOZurW55EMpuCV5WbxxRyiHi1XzvDwja99BHuyWoFXLcv5EPtEU6Se3FV66NgC6tcJiuqovFx/pVghaPtrAMXhC3fmiv5Y+6B+Y6uB+JkKpbr/3V0tElkamqjheZPuQR80oy8jMUBoVALa3e/wFT4VbNDUOhQIh+1Y123W5cRdaEbEnmmItvjyk1riHeGn/VCfybHNitjItzyKcFg2VUScXNW3xtJITh1DFqQmGwInhxHp8Z/yxn+1FDxZ89mW1P3Znrahhj721z0sMommoUqzJHSu2sXGaRCpQUFeuMzCqSeL0k9pmNrR8oSYnizKXw3YGYDTbzK1oipSiJ0XOHlmPAuZG6g28w38ivOCK7UOEDI4s2owUUocD4DgMrPC8fTJIBep6tTh/9FmS1iHIb5X2gbLSg3dgFk4/goOFlAXdKW61Rdnc2w5QhQMjHK+v5d2dcZz4R0Ux7HTc0cvUlpeOd2F4SFCVTyY/DOyqwtVd/KK/M3cLkHLw1QdenioNyuLUF2b1RMeeFAS6gOqo0Oq+RxAq2Rgcez8Wm31SVU1Ib9731bwgh3BMZBVKCPMYju37RBGnGpdjYh5SWYYxULHmWjVw1mr5yXA1Ou+KHgJaMp9pcTXt86dsL4tIKGiLo/FG9AWU61IvorRUyB5OAIF+cQUv/o+17tn73EBUgdhxI4JhpLolZh/2qCDU0fYT6eGWtJvmGCFfZ94OeBk1HRPURgge7aYpB3LZ8M+QJbnrJSchyCbSlyjc3Fdf1EsP8kBxMa7gi1Ay5DDIMio1wS1ls6t0mgS4oiOx7wBM30A1jiI/1NOzhUr20bTF+CPb5z2qg3VNuKFK/B/EI4/6PIhMw1ElSDVuKThIe9WqnAy+yisqVpkbnUFMoBsSLFc14lJfBI15gkbCRcFxSlzNMJUj2nwxc/2y0wf7W7WZUn1aGRuFXXssbczJ59a9fytETZcTu556XOmOkMhqUhNZlOXpIKLt/cMFW5Qe1uv7oF/38pmdF+Sj6o0d9rLmUpTsv1iO58DAavYmJgCtP716Bbmg8yL1nxj2bX093eHROz9OZL3i3Ld/cTs0MJVI7/HvbSm0u4fCLuwHuiMtBcXZXtlBuH/FOkewCPk8gCWzhEMQ5Y9ZB79EBYoUMsi5UTPIsgRUwFfHBgdGWDZvJBXyJAtsbB7TVZcAIZtBZXXS3DbO7CCZf6x/GibFM4bpT9YmBUzXQe8ctowwTkS3ed3k8rnMTHFbDqYeaVX1kXa1BnrRSHuTrm8SUejDvKVXFqhvk1L61VHfXTYIvL4sVVwugwZu/Ig+fO6lSW6BiYWjaYbxEexvnczWdTmegF0CdGBKe9qlfj+Q65hnXCE6Dqi6MeXt7t+ZOcmWzQFaFO0uDiaZBVNVc78hc1irQHCQnOhQQv2kFkh/HHmHIw/0vQbTadPQF9bFkSRK/Y8ja9NsFaDxvgwUH1La0+vl5WNVVMgiYJAnj8Fk6qZsskEhTPG9O2f/Wx3uMqDoe5x1AFYpza6H9mOt8tuOVsTHky385LeH4zKtg90VxrxdzFPBOBILJe2jGdz/k4LuhXCG9JANFm/EK5KVOAtVsiv8DOjpotDKKkVIhkiUuaSHSlaaHwqU11XH3aHE11Bn2BJ1Qv/I51qTAhDoFJOblj3iTK7sxAecvHCnPFQiqooeW/9lldIssJF/X7A5666bKK+L2grU55pKxhDSnUaG3e,iv:iUlxd0gNNrbqOBGYrAcZ1tRllwoZT3DlNKcjEHxPZ+g=,tag:j2eQXVrw/SDITw+33X09Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZFBXTUNFcHovN09XeWF2
            Y2tOc3lkeXBBbXlwMmFaak5sVGZ6eWVDVFJJCnBFOGtOaW5WaE5Jc093RkU2OWlV
            VzVxaGtZTFN3TW9XWE9aeElVNHQwclEKLS0tIFBvN1NKejYrTFR2dDlQLytlMVJN
            UUFsSEtMK08xemd6Vm5sZ3dpaHhCeFEKwC/ZqLdlxxvcGgMzmNbW8pg1mKDe5Paw
            JyKTIaYnN6jm7OV/ZC2qZB8gyTOBmpUf4oAoUFf5GJHcCrYlgLOmHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:09:52Z"
    mac: ENC[AES256_GCM,data:fMQdxs80IT4B6mie9fqPJnj+mhxNk18SXc2MVIr/QRiXMaZRoH1sX1crH7ldgBo7MP42/24CtKIP6MtRkFeSxPlqx6qz8jpzxH9uWDUr6vejFtly3tH/AaxoBQCKaE7+MDMzfjwmArkZ7BYoZMh34PHX58vmn1LjD5B52+E0BEI=,iv:2KB5s4oDDHgAOAC0g1EIcedErDUo6Q4PF2uDQg/dhi8=,tag:e0/mqP/HhumMUa8Egn4/hw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
