apiVersion: v1
kind: Secret
metadata:
    name: ssl-root
    namespace: dev-tools
type: Opaque
stringData:
    tls.crt: ENC[AES256_GCM,data:BNdYMocI5jxq9M9ovyPBCRxZ4HORUX2NQF0Uob1PBt+S5cSYPwkbLClp2niD7y8729zWXi6jEn3DiH+JyRnh7sGh+BHbxWbIJJMWGyhcJlTP+mi2pBDgXG9ebcAZhGJkk6P/QZjHCcfsCVeK6F9P+cAILy0xyNNSQrLSn+2W3ihZ3wa88lILiWh6tnDfUIvXotx/LBx+EVwEXyk7SIYFA6prpLKxyDgcjxYxhErsVt88+SK3sq1K9ooODWuZHj7+1i91Kzxya80rqX3+FU+asxG7wI8Ljp3ESrRKfr4a7+q20xdK8R5pz+JVq3XDh8dkzosCwM2c0prwdox0/RHsa5IHPb3+S/SRfSEzS2h5iNathMBnX07oa++zzWFjlYHEnHrt0ilQXKP51eSpXX1h1Eu98C44TeWAW4997dHWQGxFjgQgTJM59Sh4UmIzyu1gqnxO8iAUg+0wi+SGIE09MP49qHSM8XSQsHMxkkQ3Vd80FpGecCjc23URoA20vuqeapyddm5DJE2lh0c+/bwYuXHtko+01ALvQCoka+Jg9nTzyEb4ri6v+MjSOXR4ZL5+sJDpnQdSgB66u5TBeNKfnuelDOBlc3si7ofH9sXNmNgCbNSW20LkWlMhJqg2GrWCE8xIgwHPMmMeaYjKBvdeNEyrjXGZaBzlOfr+4n1J5kVSg8Usx/zJp4bv4SKoaOgwLPO87JPMY0NqmjFaHHayU0lIMAHI/s1OntniSxPWM1VAZs30qGDD1YXXW8UIkUF2trmb5MGfnS8ZMS8+heb/PdkZzWGoO+jGd8L8kxEMkltUVpJPbCQ8bXZuKTDPTf3U6k4b16yU7ZTm87ObRPo45NXnRcTRPQjKCeVcrGGhBNU5O0dbBrzxOYpzXFZjEEVextbIbyAZZ7P2BQwiOUQ+hsNlCp8+V6cZ0moyPuOiMVi+VUemjYILlzTX/6G1Mxtvj68OSSGSRhMvOaUVsME+vrq2xCjddaRxpNJSiZkGIdtx9On7fY5gBndI9DwVfB9ZWAYWbg89Lq+n96t62yEVVteHT7U5we5Hu1WxcuvMZaMJqqMuNiPpavJC5tJHTFTSML3xGxT+Ha1Do2k9du4kiJcdSFtwwhaKXeej0KixzPg8oGYXaX5AHs71mEg/59PXEu1zAVRFTmHQWpkk3cNqWIPRAad0BNV+V3i+AIgK8tIOegNRjf/ZTdBuvx97UXkV4nnyMtMOsu9StTskTzEPZERMzPUspTikWBCvRJQZEW8zdNazOJczwiRp1NJakRZYeTwQ1urrZNX1jBWHhkrb2R/jaFzqKsTZfg/ByYYhlYoctijPFctFZL46CPtLcXA8UUuvSxy0jZfISGipROP/hZuSLktt1udgmhxU43NJH0pRDw9M2RqTz72xaTPvY3sMe8dXQqGbP+7xzwhauOxQ69yANh5YXj8NYBFXx3poWXTvsdeKedqzKtIABRR8KUd7Ht2eLpS+9b/8oZrvsRA8CuaSttAVjGDeFkLHL6KVtktUwwcWy3mjnYtP7bympiHuFgC3QVNHLCjdUf+3QY1NKgZfDC0eyeWIYSBCyqOM9ncKZe2zfh1oxykPANzs59Tr1j7FvRjmEd9C5E6RwYujWnj9+iYBxa9JEskFuk9ZQkkOOJWW714IChGEkpG4RfSTUvTXtknUgPVM42haX/9S3fVzfBjTquusFEj9cIVhKSb5c+7UR6Rq9iyOrUtGtYGar2bmsK/gl/llpoYQAVhdLgmVYd2PfKcC2Qp/qTYP4thUkwn3sc1Gwqfw4rmStR5xMkqoNcSk,iv:BUVy7fYK0Fotwaw4LCxtO3Afpcvz8s//SbSNRS/2xpA=,tag:jFTi9t3YhQjyxKoTWBH/iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQlZJR0IxTnhLV21QTE0y
            WTZzNG1LaWg1VThvYlc4QkQxcFRtZXRYd2xRCjN1a2JScFltdDRxanN5aVFXczZy
            SU1QaG9lTWJnTWJjREI1azRDbmQweVUKLS0tIERMaitrNmFQY3RkTTVEOW1BOUtY
            UmZaNjZ5bE0vclhnRXoySGxsRjliVjAKD8dFxMGXEZEHjIOjFSHq+91LuOwLfs7I
            ks2bBwiKze/UcDzppsI4hknqkrVeMCF89uZ70oz3qsyUWZt7EA5yFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:mPaapo2ifbiMyQQ55p/1M26WFqhwUB+0ATxRKNYNKpuc1tABvytFTn2XiaMVLnnjTzp1mRWrNkd9xqkPI2quA8bGtwLRZtePiAG/Erui3VE6/H+V5tpMd2pAZlGoixjkHbyxvByWKnpHI0mQ34oPS+5bfbx3yk+xf4ttY7c6mNI=,iv:2xigDXOOjf1dDeqf8ZZu5774DqySwNH+++RpAv24UUI=,tag:+rJdCjlC76O9WD1sFhfJtw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
