apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mana
  namespace: app
  labels:
    purpose: data-mana
    database: postgresql
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
