apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liquid-cert-manager
  namespace: argocd
  labels:
    name: liquid-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: http://gitea.jbernh.xyz:3000/jxbha/liquid/
    path: infra/kube/platform/cert-manager/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
