apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liquid-bao
  namespace: argocd
  labels:
    name: liquid-bao
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: http://gitea.jbernh.xyz:3000/jxbha/liquid/
    path: infra/kube/platform/bao/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
