apiVersion: v1
kind: Secret
metadata:
    name: brevo-secret
    namespace: monitoring
stringData:
    password: ENC[AES256_GCM,data:5/0m+YlYIT8NuHJrR2/jjA==,iv:k8vIMGcCgE1R1Lnorpdxq397sHbzMDZnJAv5flOgziE=,tag:6U7QsKVmUsCWUOzZuJUdaQ==,type:str]
sops:
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ3J1b3F0RXlzNkErR2Ey
            MFoweXpZb3VzbE1HMWZyM2ZuSFJSVm9rQ2wwCkhYclV0Rmh5cW9pY0xHbjlSN2Jp
            NTJZVVFtVnFjZ2l0SExYZW40cG5oQlUKLS0tIHY0bU96Rnp3QyswQ2NXQk5oY1dw
            dGl3Nk4wa21SREdRM3JVOXJSNTRuUlEKXgY7Trb8rdlNiSyvAdlWyGJ+Ngtbe7+k
            ogcgfyqvuS8TGtHGm32DIIpXnIm3TVATUxDC0PP07l4VLEM9+DGlpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T05:16:33Z"
    mac: ENC[AES256_GCM,data:G1xRXZ2bDAdacldIL/TgVm7tQjupqzjtON8Xg2O/acVzXeftJ46KDGLJRepyn2AqaN6YADcr9k8HqVpsldDKqem04/A5OWuN94MLa+PSCpoz9nrMi7m07a/MmpBDrA1+/2/D+J88kyCwKJgiXQ6wiUTYx1m4abh7Ez08dRHbx24=,iv:LlnoUaTYHm5bf4dspcS+2k0n0VuZpqFkgpSz3qjV5ho=,tag:uUHzjWlqm9fZqahBnbV2yg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
