apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: dev-tools
    labels:
        purpose: data-tools
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sRcC70s4klw=,iv:9OBWS+LW/RCC5JZt0oe6di8RRHAQK9o6P8IOOZ/MU4c=,tag:xyi9ac8UsL7tmj7DLc1Ppw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ExJArw==,iv:XxXUSNGj+gVI1VmPc6ahQyXSerbEGM76tpXqB5f7tzo=,tag:qNrywmpKrhucZ9RWAR/1sQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:n8ehTT0=,iv:Vx7Sp0wyzo7RtgHzmlPL4tYyItxXmuc8mNnO1uyauiQ=,tag:NF0BmhsJVkOntbPDNAUp3A==,type:str]
    GITEA_DB: ENC[AES256_GCM,data:PT/2ZKk=,iv:sO1uE1MlmtK/1SHaWCqZlAOc2eqbR+e8Kwjw8z4b10k=,tag:2roI1X17DG46/gq1BQnZIQ==,type:str]
    GITEA_USER: ENC[AES256_GCM,data:rKxVMbw=,iv:TWPak5uRnzI1aV8bk93D42D+5NjNrcM28jh5buczwjE=,tag:Wh/K5v3FVV1gM49Cwbqr0w==,type:str]
    GITEA_PASSWORD: ENC[AES256_GCM,data:LUJehAf7Y+J87+klnv09,iv:dRrV6e6ESooGGBI0Gfd8UKcAZdq/78KD/qI78Bt6EZo=,tag:gxMfVkIFPAlfRHpMwU+eqA==,type:str]
    DRONE_DB: ENC[AES256_GCM,data:cDXD8l4=,iv:IDCczZkZRjda/YxXce6EjzV/gUZ8m3J2JgiA2703fVo=,tag:y/fD2nTiY5IA0uG0Fnk5bA==,type:str]
    DRONE_USER: ENC[AES256_GCM,data:DhHsJh4=,iv:EWag8quS9LnpJ70seXg4cl8X2jFcJg5a0Hq45KpqpDw=,tag:Hfjgavs02MVoJ45EtdApqA==,type:str]
    DRONE_PASSWORD: ENC[AES256_GCM,data:TBjfPn78l8YyTJ+i/+Zj,iv:xUXZ+kaU1PNIlXgjy2S8ojXBNuesmWiLDdTkGcc9kf0=,tag:sAVNa2FWpKqcR7RcUzIptA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMTJNVXFpZjROQ0s1MlJE
            SU5FM1c3SHJvNmhRbkJvcWJYY1c4NlpOOEdrCldac2I4U1dndTVkK0Q3dlFqWjRL
            YkNOYWdqamY2NmVkY0haYVU4UjlSR3cKLS0tIC8vRHI5cHVhL1BnUE8vT2dKSG5E
            VUFOd3RvQ3NhanZUcjYzeWtENzlYQm8KqUorSRThBlfdaAxn4n167G12gGFJGfZc
            9Dv+4g0yL3qbU23YQ7q8X+it5ZlTlqNFD5ADkjOlB1+sq0H+KelWDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:UvZjTGyq93myVdhkQT38TVZgZfIUKyLBUYI7PVRVRgxU7dQlsyyjPDmQjbhFNkQNRbkhrYPn+nqgIP4JuTqemjfBNPeP+QQNTjcEULtEtWv0rOrw2DgIUY1J6zSN9OzKadxkay0NmZcfYd5aU8oKkV92HiISjYZ/WOGCny7kI9E=,iv:MYyHAeLULBf5xdPxmxfgMLUrQPZpLp+IusYtESo2DsY=,tag:OtU+wMTIdjQVEhxHKfyeAw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
