apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: dev-tools
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: dev-tools/db
        property: postgres_password
    - secretKey: GITEA_DB
      remoteRef:
        key: dev-tools/db
        property: gitea_db
    - secretKey: POSTGRES_DATABASE
      remoteRef:
        key: dev-tools/db
        property: postgres_db
    - secretKey: POSTGRES_USER
      remoteRef:
        key: dev-tools/db
        property: postgres_user
    - secretKey: GITEA_USER
      remoteRef:
        key: dev-tools/db
        property: gitea_user
    - secretKey: GITEA_PASSWORD
      remoteRef:
        key: dev-tools/db
        property: gitea_password
