apiVersion: v1
kind: Secret
metadata:
    name: mana-ci-secret
    namespace: dev-tools
    labels:
        purpose: mana-ci
type: Opaque
stringData:
    DATABASE_HOST: ENC[AES256_GCM,data:JGUyITMo1RhXmPF3x1Jx4yKAXbYN0nH3IKGKRt19qoknAWrisg==,iv:qsRaVmMBH/13Yt/D9+a5RlYes/hv3w80lRfNlLqBByM=,tag:ffb90UKk5nt8HxHyIkO0pw==,type:str]
    DATABASE_UN: ENC[AES256_GCM,data:/Ehbsg==,iv:F0+7mkKFvXlkoi9lS74bUZ1M9j9xJ69JMiGoO7T0Tsk=,tag:oZVAxgPX1AeqjkIzsYVRnQ==,type:str]
    DATABASE_PW: ENC[AES256_GCM,data:+TwYhtkGL7k=,iv:b+/xtAhnwpuhoR6D8uer9Jn8LsvjMUa0M1KMY7C6PMk=,tag:O8ig4IB/kOlc8gxPHu0wag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M2s3QzR2aU84cjczMkUv
            U1krWDBQcWh3MDVIYjVIbkRVT1ZGNUJPK25BCkx5eE1RWkI2d3JGck52enNPQ0Uy
            M2xQYmlhV0VGcExZb3FwUHNsN0lBaDAKLS0tIFZZTGJKdjRtMkswSTJDVFl4UmRV
            Vld1a2tDZXJnWFZibHVxZkYwdUZCK0EKzO2VpdlvXU5FAGfgrSQ+qU4PihKo/ac7
            vvXrz0Myhf4s7U4CQrhx/H1FxSRTRUIy3Uahrykhw/gVjA5pD6d12Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:KTU3p7CGs3DrC0ZRloZBy7lP2zOG3Xar6DKCL0/RBFSYADjkGgeNAe54Zt8tayz96JsbX+hzoMBTA7QhK5Tevod8YWWV37u+HQJsedR2O9D0kXhtxG/VMaNnHCvP+6wjioRzbYUYb9piu+412gXx7AFvyUUbuvZ5BFC67SrPeSQ=,iv:osKzrkdtzm1YqdUogDnls01+ii0gA9noWcx0CkgfguA=,tag:FEaOyjebXZsBvs18jkCJ5Q==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
