apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../vendor/common/
- ../../dev-tools/
- ../../mana/db/
- ../../mana/app/
- services-nodeport.yaml
patches:
- path: patches/mana-scale.yaml
- path: patches/gitea-endpoint.yaml
