apiVersion: v1
kind: Secret
metadata:
    name: mana-secret
    namespace: app
    labels:
        purpose: mana
type: Opaque
stringData:
    DATABASE_HOST: ENC[AES256_GCM,data:o+5zduAlyL0lbEFMP1NL02WPu0Iy8Xk63H6Z6FCPC8ecElfTlw==,iv:zDmIXseU8ZYD9tb+o7iU0+UL3mgPu0Yq8jr8ahCOHC8=,tag:xyUgmQqLcQvC2QlCZy5TYw==,type:str]
    DATABASE_UN: ENC[AES256_GCM,data:eu7JnQ==,iv:CdL4YWc8jkTmk4ylMRULB4BOuXtY1v9iF3fbo/O7Ndg=,tag:gz6uAxHh7hBSJFA06vb7OA==,type:str]
    DATABASE_PW: ENC[AES256_GCM,data:TDdqwApq0m0=,iv:Jn2OlkgfVcWS1FG6uF6lH/EVs8jVkVT07L8A/xPgqsU=,tag:90EiL1cB754mrC8fp8ijzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMDR5dGRRM0VLM3ZZNkxi
            UVlLZTJ5NTFJUGJKTktNNFV5YTQvelZKeWxRCjdualNPdllXQXVMc1Y5Qk5XVyto
            b2pPWDJ5MlgxQjEzTTBkcnc2clg5QzQKLS0tIHAyYVZxRU5oVDhUZ1NIUldyM1gx
            OHgyU1RESjFBVjIzbjJOenhkWUVDTGMKW5ApImG8WP06LTzg2RMm+i2jX8QceRgd
            2M1j3uRCShrPE4Yqf0DmJJMtay2/VwmtRqb9FrtTb2dOFJaeD7rsLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:5swm5XCgC20IsthRS+2kYfL0/u+ndrpwxnKk4OI695ujz2+U3uJO8A/Sq6UlPESFthxUENBVCaadfoYuqBETJ7zgUuJA6rRsPUDWjFkly9hsQR5dSoD7/xqDce1osXsQSFDT/v2B6Xp19iTkuoYB58hHfSboftsdWNu73DAdAjM=,iv:s++9/P0HajDso+r94UIG33Z5bsFWKYocgivHDmCeAT8=,tag:pFfh9zL2HOpvurMYaQd+RA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
