apiVersion: v1
kind: Secret
metadata:
    name: mana-secret
    namespace: app
    labels:
        purpose: mana
type: Opaque
stringData:
    DATABASE_HOST: ENC[AES256_GCM,data:NfhoHI8qTkI3FbNn0b1vnAmhyEAtWaUUTTHKcrkgENcvL0aLwg==,iv:ajnNyUHlIidBESCKhu9S5OgDH5VDg9krlXDWzLfFIhI=,tag:JtUhbUzy6Osq2dH5tLozZA==,type:str]
    DATABASE_UN: ENC[AES256_GCM,data:f6LbEw==,iv:WZHeUjcDGO3+mC21j6zjimGByb4e3SmxIb7wg2tBboo=,tag:t2kXS3ObEtqHVFq54MLabA==,type:str]
    DATABASE_PW: ENC[AES256_GCM,data:kZhwClWzR+U=,iv:s2cihDy6g5orSVXm+v4oGCXOwEenFFsNWaaj+gsAVq0=,tag:Rpo7T5QhzKE5/T5vFPuHZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK25KSEZhWVg5MjRuQk5p
            WVV3bEhCS1VXV1NwMXRJbnNRNU9MRjRJYXhJCmlkQldCeThwM2Z3Z2U4eTN1OG5r
            YlJSYVFwOVZra2haOTNvQi9ENXZpKzgKLS0tIEduM1lac1o1UGpscUNqa3lKTlZR
            TUdPeW1tclJiT2N0RjhDOWt2NUx0QTQK2+JDBd8Y3EeatymNPrMRwZZ9CVJNezSv
            giBWF5SoSSEQn/DecL2u89EdsoOQ70HE1pfFEPxQ7aqoQ7Ou3xuX1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:09:52Z"
    mac: ENC[AES256_GCM,data:BMWtIO6zfxc9/uVHpfue12Ar28RCI5Cay6Zj+ZFCFjeetSl167ImC+5+gZaPZrMtAQ1HEO/S5C2DYFbbeTMUBjk2Khj4d7v4OH0462Yga/uhR+yaZPsZVDG0zFlRtEcRqiHhV0rsdaBSGA8NRwXamqzfzDW3FaQP0JtvaOhKrxQ=,iv:D0kfAqVyyh95XaCNwaSwlWqbPJCYv+G2mCScF7phPZE=,tag:hHLIBPk6l2ACZSCErMyl9g==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
