apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../vendor/all/
  - ../../dev-tools/
  - ../../mana/db/
  - metallb-config.yaml
  - services-ingress.yaml
  - services-loadbalancer.yaml

patches:
  - path: patches/mana-scale.yaml
