# Per tailscale's Helm values.yaml:
# Operator oauth credentials. If unset a Secret named operator-oauth must be
# precreated or oauthSecretVolume needs to be adjusted. This block will be
# overridden by oauthSecretVolume, if set.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale/tailscale
        metadataPolicy: None
        property: client_id
      secretKey: client_id
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale/tailscale
        metadataPolicy: None
        property: client_secret
      secretKey: client_secret
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: operator-oauth
