apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: dev-tools

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev-tools
  name: dev-tools
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner
  namespace: dev-tools
subjects:
- kind: ServiceAccount
  name: drone-runner
  namespace: dev-tools
roleRef:
  kind: Role
  name: dev-tools
  apiGroup: rbac.authorization.k8s.io
