apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: dev-tools
  labels:
    purpose: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: drone
  template:
    metadata:
      labels:
        purpose: drone
    spec:
      volumes:
      - name: ssl-bundle
        emptyDir: {}
      - name: ssl-root
        secret:
          secretName: ssl-root
      serviceAccountName: drone-runner
      containers:
      - name: runner
        image: drone/drone-runner-kube:1.33
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: drone-runner-secret
        volumeMounts:
        - name: ssl-root
          mountPath: /etc/ssl/certs/root.crt
          subPath: tls.crt
