apiVersion: v1
kind: Secret
metadata:
    name: drone-runner-secret
    namespace: dev-tools
    labels:
        purpose: drone
type: Opaque
stringData:
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:S2Ed7NoolHIqKXlEhk+c0e6Kmz7eqmLsAvCYFll6CKM=,iv:qfhq7+JLfCHHBBJ+Lz8gL7arqpovdciLLTowp6xlB1g=,tag:IRGZqAou2VLB1VNdIe1EnA==,type:str]
    DRONE_RPC_HOST: ENC[AES256_GCM,data:yBeekL7MlRnGrV4UKk4R6x5iJ5ZwndLwxsJ2t+Kd8ofQ,iv:Ks521mcsuH8BpavzzVihT3Bq21DZPDYher9A6Z4HPUM=,tag:tscx1NZ3as4Izi4k8R+0Wg==,type:str]
    DRONE_RPC_PROTO: ENC[AES256_GCM,data:P0HN8w==,iv:e/crEJh2hoT3AVGWSzW4ZK6eFuToR7g40s+1iqE8tas=,tag:j/N8fT2TEh1Eg779jugtdg==,type:str]
    DRONE_NAMESPACE_DEFAULT: ENC[AES256_GCM,data:hSfRJDnfZ4KO,iv:n+spMEHYVxnzDxMILRUTEJI+u0htUZipjGdsjAsYZxQ=,tag:iIUjh0TUd2yovgOn4ycU+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYmd6WUtpbjVvb1JOUkZr
            c2RMaEpQWGNIRGRQaForNThXRm1SNTU1ZEZzClUyWmljTWo1Ym5QUmJkZDJ3ZlAr
            NVQ2Q2hTK2JINGp6TEcxejNqL0t4eWcKLS0tIDRndDdsaHVDajJpQ05XOG5Vckhh
            S0ozQXFxZlBYRVpnejZ6SWRlMUlMdlkKon+tmyImxt3DQ2z1YWLbzc8A3lfQqKWR
            PjlWmKIzMjXnf2N6G9fw+IweyG4AAQxcU+2xq0r6GcgQ05LrjLtuPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:fUReNK0OUUccjPuff0qRazWUwm7PWvOyNRAiuKDAuU4evVUbTdLajyhab0wFGkZb7i5vcdNy6Ak8Uch0XEJCNwgs4Zau0N84Y2ff7vOGnJmGqevlKxre1sfV1zHF3Ptyea/Nei8DM0jfgZzeriGBmJl2lc9dBcBFZqn9On04nno=,iv:z6ZF39MqRa0Sk/e8Wr4H1HYYz/l2zBSmm6iVa7OuNqI=,tag:3vL7QXPLetbPhC0lzcz8/A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
