apiVersion: v1
kind: Secret
metadata:
    name: drone-runner-secret
    namespace: dev-tools
    labels:
        purpose: drone
type: Opaque
stringData:
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:y5UhoiMoTt4Ai11melUlkcYEkoY3kDgAmjdR6zIPmc0=,iv:FbuUq2E861DSNbtxOUvbguYXZT8bmaufkNie8/Ba5yY=,tag:/m+Yx4RvmL2FufJlq/TCsg==,type:str]
    DRONE_RPC_HOST: ENC[AES256_GCM,data:jU6CCNxT+JSTA3hn1nDgFbuNPyFUiTKNIZoXx1DIqNd/,iv:WLlhGFDwVKUeS6rHP6zgJuKAKiBsVnn91X8J1aAGOZY=,tag:u/O60bvfALioW5tYyr3Wmw==,type:str]
    DRONE_RPC_PROTO: ENC[AES256_GCM,data:67jcvA==,iv:YpNZ0vYNyX/ZHfLpKWmdLQYhJ5SmkSOsYRwxvrMrHhU=,tag:kGZtTxAfaLpidGYmQO3DjQ==,type:str]
    DRONE_NAMESPACE_DEFAULT: ENC[AES256_GCM,data:YmddIkBSs6XF,iv:2Bcj5ReiCPnn8yTBpjiPc8YzRm3a08rrqVA+9/QqZo4=,tag:o6l/xOv2YwrQ9yYdN8VubA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuelcxK2N2bWpCVWdoZExy
            Qk5EZkMzZVFkSW1SNEVINWhBZnlWTUVZMVJzCkZJd0R4L2huTWFJbG0xVmppNEl6
            QzRtZUp1VnN3S1JtWWxzNFFRdThBMTAKLS0tIC8zd3NMZ0loSmE1aWZhU0d3US92
            Vnlkb2JLVVRTUExmaExza1NkSi9rcUUKVuf+xs87mMwD9TzOIU9b/dVAsHQauDHl
            JldPQklh1+oqqbAGLOoPMFgtTnc3YiDeIj6CMkQNoCsI7f5DtsxJwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:09:52Z"
    mac: ENC[AES256_GCM,data:0fa52uWaRwDcKLpQ1Faz36Xr2sJ3aoAG0EhxJeeMFWTiIFAoFI/CnDPLBWW5MxJ0ezlm6IdeGsEt1BsPXz8VdE3dJvTVbDsrLR7MSwa3/fAUX4Xb+CCYRJgrFgXsv9u1Cp6/LNUfKIIvEGyKUBgCReEt0uazTFnLD5ewQmjNyxs=,iv:/WvhnchUh9hJ8PQMgzrN6PXMhLMs1Lh2x8yIEyyrMtk=,tag:38HNkNOTOrBvd8rVmAN4iw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
