apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-registry
  labels:
    purpose: registry
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/opt/liquid/data-registry"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-02
                - kube-worker-01
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-registry
  namespace: dev-tools
  labels:
    purpose: registry
spec:
  selector:
    matchLabels:
      purpose: registry
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
