apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-registry
  labels:
    purpose: "registry"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/liquid/data-registry"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-registry
  namespace: dev-tools
  labels:
    purpose: "registry"
spec:
  selector:
    matchLabels:
      purpose: "registry"
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
