apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: dev-tools
    labels:
        purpose: registry
type: Opaque
stringData:
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:2duuY9ewWYVXR6xM2MEL,iv:PHkxFvvdAsjkCEXvKHeNDhoj8aHm/7QZAQ83nXpW0mQ=,tag:Eeegi/IwYzGXMcHw9DvI8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUjZhV3VKY2V1Ym1xOGcr
            b3NzaEgwWUhjdFpmdlFyRUhSUVBIenZkS0NrCnlRRXBpbkVMd2h4M2tEcGNWTERW
            cExXQ0FEbDd1bnozTG5OZzF5YVlocEUKLS0tIGNzbWVRU0VqdFZ5ZHNpd0ViUnJU
            dGx6aGNhVnhkRmxXanpudW12ZEZoQm8K6+mtZEM+j6bJO1WB7YM2NS4bfo2oyNPp
            5jA/OPSnzaRnOL1kAQCTsrfS+ggldGwjvN8nrh7oS6oAzvnVeDJi3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:SEHzSkahuhAmFfaCY2x9scHGQ/1SCVAE2Urw7gZJ4LLiRNaq/nyLTkufX3Qw2vg7ZjWatuOhl3watOhdo5pxiD+wgYwwKzcS7aV2xRAAWdhrrz/7Dxe80NL42FEEWgqRv5MgQSpB9IYGz5L26uzMmoThnHtFIDbTRA4wv08sNfg=,iv:wNwcxLJzgWxz9KuoftkDuCaoSbv0idsahCJqrdGXUf8=,tag:WEkDdpktoLBOXCirsIV3sA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
