apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-secret
  namespace: dev-tools
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-secret
  data:
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: dev-tools/registry
        property: registry_http_secret
