apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: dev-tools
    labels:
        purpose: registry
type: Opaque
stringData:
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:N53/ls6YRTC5OZJaBe37,iv:6cNkuF4S1l6FKcWDfM27qHZhOEbsTF+roiDJ7QJSj08=,tag:EpHTwMmH2z/WujbaKvLQWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWm1sNW83cnVFaEpKUEVY
            WFU0ejdjdWtqUkpDNjMvY0FrUFVLNEdhRVR3CnBhN01HbFE3N0dpWmFlNTJXWHhS
            aWYwKzV6aXViNWpnd3FXZ1B1ZHc0TzgKLS0tIGJYN3h3aWMxRHZnWFNwYldVWGJq
            RHZNaHBQNDZBVTNjcjhlNlp6T3d6NUEKe9dJJJRrNvUMuNIX4meeVk9Xc5YOdRh5
            gZMlEDHnQUCIJ2e7rz7Ye2Pj8bQdlnbvK5EPfmjQqL/eLSGsh/Gsow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T01:05:25Z"
    mac: ENC[AES256_GCM,data:4JBqypg4AqiSX485DLmtu4VToGMye6hrrPZY0OhFE/PjIIFRZufbcFf+UW36cRYLQx795YtcDOdHa2n3POBrJ3TCxCpVWsdbFJ92i2Iy6Ngc/7EUSaJXDb2ARdXVkecteX9Y470JIq1MJO8Y/Kb9IdutIj+nHh8JYxBdGZVK9U0=,iv:ppcuvxIPPSuvqUQ/M18j0u3mtsVNu9So0in0a/L1JbU=,tag:8F/PVA4vEbMZfPWdNqB2PA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
