apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: dev-tools
    labels:
        purpose: registry
type: Opaque
stringData:
    REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:X+SaDskp4WZRAai1ZP/4,iv:QiU1ianOgVmfLyuZvoN1cm4uZPTKe9jpc39SUrqbzWA=,tag:0+Ef9RuzpChYkHwHFJu2+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYzluRUdvN1cvVE1tMEhO
            ODlGZ2E0VWFxOWNwQlJiYWRLcTJKNmxnTEIwCmNmQjhGTlhoeHNFQi8rSFZYaExy
            M2Z6M3pXWk0wQmpZR2U1NUo5U2JsaVkKLS0tIEl6UXZicEpPV3FMYUV4UlRvN0Jt
            RlYvd0RPRjh5U1dXNUVwYmhmUEFwSmMKwan2AD/jLXoQ/g8/N73JjLqSeJIQHspR
            kjsBVW0pvsyL+TMfhxw/HfJuUJQHW3fRN5DEkSRX8CEKAByDg9cKog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:09:52Z"
    mac: ENC[AES256_GCM,data:eDrudEfpqcbkHCl8GeBjQNLmvas9GzkfdxIMkIj3qXOPSYgIrk8/9xGI/tZAO32GoPkAGsA92T3/zNjx3tNfrH4PuSIwYXT9bcK0+N5PHL5l5Gdp9R6SybhninGoUnwuoR1nHPcxaDJy1vnnVfmFmSe3hJ42SGGWrnSGi6Uzboo=,iv:ZgyoBq6hOXc9qFJlMHmXmEFYcaoss4yJ8XbBndFxREw=,tag:0If0qMRwiJrOjcpsriu3yg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
