apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: dev-tools
spec:
  type: ClusterIP
  selector:
    purpose: "registry"
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
