apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: new_image
  - name: registry
  steps:
    - name: deploy-mana
      image: registry.dev-tools.svc.cluster.local:5000/kubectl:1.33
      script:
        kubectl set image -n app deployment/mana mana=$(params.new_image)
