apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-build-test
  namespace: dev-tools
spec:
  steps:
    - name: unit-test
      image: registry.dev-tools.svc.cluster.local:5000/helper:4
      workingDir: $(workspaces.source.path)/mana
      script: |
        mkdir -p $(workspaces.source.path)/gocache
        mkdir -p $(workspaces.source.path)/gomodcache
        export GOCACHE=$(workspaces.source.path)/gocache
        export GOMODCACHE=$(workspaces.source.path)/gomodcache

        go version
        go test ./cmd
    - name: build
      image: registry.dev-tools.svc.cluster.local:5000/helper:4
      workingDir: $(workspaces.source.path)/mana
      script: |
        export GOCACHE=$(workspaces.source.path)/gocache
        export GOMODCACHE=$(workspaces.source.path)/gomodcache
        CGO_ENABLED=0 GOOS=linux go build -o mana ./cmd/
  workspaces:
    - name: source
