apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: mana-binding
  namespace: dev-tools
  labels:
    app: pipeline
spec: 
  params:
  - name: repo
    value: $(body.repository.clone_url)
  - name: short_sha
    value: $(extensions.short_sha)
