apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-mana
  labels:
    purpose: mana
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/opt/liquid/logs-mana"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-01
                - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-mana
  namespace: app
spec:
  selector:
    matchLabels:
      purpose: mana
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
