apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-mana
  namespace: app
  labels:
    purpose: mana
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
