apiVersion: batch/v1
kind: CronJob
metadata:
  name: pipeline-cleanup
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pipeline-cleanup
          containers:
            - name: pod-cleanup
              image: registry.dev-tools.svc.cluster.local:5000/kubetools:latest
              imagePullPolicy: IfNotPresent
              command: 
              - /bin/sh
              - -c
              - | 
                kubectl delete pod --field-selector status.phase=Succeeded -l app=pipeline || true

            - name: pipelinerun-cleanup
              image: registry.dev-tools.svc.cluster.local:5000/kubetools:latest
              imagePullPolicy: IfNotPresent
              command: 
                - /bin/sh
                - -c
                - | 
                  for i in $(kubectl get pipelineruns --no-headers --sort-by status.completionTime | awk '{ print $1 }' | head -n -3); do
                    kubectl delete pipelinerun $i
                  done || true
          restartPolicy: Never
