apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-cleanup
  namespace: dev-tools

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-cleanup
  namespace: dev-tools
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volume-cleanup
  namespace: dev-tools
subjects:
- kind: ServiceAccount
  name: pipeline-cleanup
  namespace: dev-tools
roleRef:
  kind: Role
  name: pipeline-cleanup
  apiGroup: rbac.authorization.k8s.io
