apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-tools
  namespace: dev-tools
  labels:
    purpose: tools
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
