---
# sudo apt-get install -y apt-transport-https ca-certificates curl
- name: Install base packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: true
    lock_timeout: 300
  retries: 6
  delay: 10
