apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mana
  labels:
    purpose: mana
    database: postgresql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/opt/liquid/data-mana"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-02

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mana
  namespace: dev-tools
spec:
  selector:
    matchLabels:
      purpose: mana
      database: postgresql
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
