---
- name: Ensure all hosts are online ready
  hosts: all
  serial: 1
  gather_facts: false
  tasks:
    - name: Wait for all hosts to be reachable
      ansible.builtin.wait_for_connection:
        timeout: 300

- name: apply common configuration
  become: true
  hosts: all
  roles:
    - common

- name: apply kubernetes configuration
  hosts: all
  become: true
  roles:
    - kube-base

- name: Controller init
  hosts: controllers
  become: true
  roles:
    - kube-controller

- name: Worker init
  hosts: workers
  become: true
  roles:
    - kube-worker
