apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: vault
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: bao-init
  namespace: vault

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bao-init
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bao-init
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: bao-init
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bao-init

