apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: dev-tools

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mana-deploy-role
  namespace: app
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch", "get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mana-deploy-rolebinding
  namespace: app
subjects:
- kind: ServiceAccount
  name: pipeline-account
  namespace: dev-tools
roleRef:
  kind: Role
  name: mana-deploy-role
  apiGroup: rbac.authorization.k8s.io
