api_key: ENC[AES256_GCM,data:+dxQ5KIqDJI9wRYrE+Eyug==,iv:YsYg/KvP+yElJul9tJYkap4XWzc6ydJeowYMdgNuyMg=,tag:S9uayvVoFNqMk/uOgnOckg==,type:str]
sops:
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdkdqVm9XV1pHL1p3Qkt3
            Yy9QbDZFTTllTWtEVFdMeXBXczZjMHVYZTI0CmdDN2NyMzAxWUdHRTR0U05YRWwz
            S2ZLOXV2S1ZYaFNxMGhpeUkraHBCVkEKLS0tIGxTZ3V6ZlpIcndEM1BNbVMrTExx
            M1pKVExSTWNoTnYzRm1kREJ4Nks4WDAKdvPDJ5K2vf+Y3DvtEyZ3LaYMEZjNf5QN
            Bz4ZEdBYz0BWWqVlJq5Nx1v14webGIGCqScDJPxZlVhdB4gQvJ3XCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T03:47:43Z"
    mac: ENC[AES256_GCM,data:yL8rO2+lQekN7UH555uiCFONcnnqs0jHErHwyO5g369CtdpC/NNTXd8oNgpNeS9eko4p+jktRmKsY+/O1ccIJ4qGoNwm0QX/t2ch937kjIHMAd09pAkqq0jtgyKJqEn/N0lE/d/xJyxU8b/8SU6AJoPe8NRGCPbWRPfL/A8naDI=,iv:E+TTyKePbq2P+Sk9lqG7t1YD01FbkN0fk+2Zr079YWU=,tag:UaLS/eJwdd72YxMEr3KwLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
