client_id: ENC[AES256_GCM,data:D4QKJWh3051l6wr8UN5AxyI=,iv:nX+Sd5LwIxyRW+u82hZZVP5aB7AvlbFP3dieREmzv1A=,tag:YrhPS9kg6Al0SgD4/hBP0A==,type:str]
client_secret: ENC[AES256_GCM,data:aG4r9Qin1zXAKA2B1pMgxnBTiWsh8OscQ43KBn8Nwh52bW3ss6YOEEgAfOuu+mgXg7CCfBeGh9x4GSp4Mp8r,iv:ENIs5teA+1aNYvCs1u07OnY78fEk1iOLyi+FbCJo3Ls=,tag:sG0mIip3V+EKQNFw8vQuyg==,type:str]
sops:
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVJwMzB0cEM3cXFSb2Fq
            RzZPOUM1bmdMR1ppQjBBdWRuSXBOQTdUOVJvCkdMSEFWS1hnWkhKbitDNmtra05l
            NHpqTXBkc1VSc3IvbmN6VTI1WFk5azQKLS0tIHhFalZBSFcrdk5MRzdnK1hnWk5n
            QTRmbURyVWRTZXlxYkVFWG4xaENmdDgKoUY5H0yDa5N+AfqIFeRVKTEhCKeA5EwP
            VvhuNz3Nqd01T9qrJP0kPTBkdBRHA4ir1qJUZfoRNh9/Ju18+DLzqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T03:47:22Z"
    mac: ENC[AES256_GCM,data:NL1qYl4vpyUCzJ2TTnyC8A/DonCkf9F8PdkS7+S3E4F9jn6DoVPzyW3yOtIjqL7JStLfRdfivoOycGKMIrvMCbHvb4+cn5EHAif+1ZBhkSJiaABNd3lTHHpmipadZF/xtpSQPAIIMXEYeEE1QUsGieyxs+EmzntPQ5jsg06a9Po=,iv:0kb90Y202AleODT+aT5KVyKC2ujPHdZi+5r7GWtsYdY=,tag:9L8LQXbpG7GhRlXPU9VciA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
