apiVersion: v1
kind: Secret
metadata:
    name: drone-secret
    namespace: dev-tools
    labels:
        purpose: drone
type: Opaque
stringData:
    DRONE_GITEA_CLIENT_ID: ENC[AES256_GCM,data:LaEDBRGUAaARY6HwR7G3rb9QF/EjE21PaMhOqp/7KMJgs63g,iv:dJgPMeqtuGxN9oWVyYNWgZOJ9oY+TzQ+gZPXM2m5BYo=,tag:IH6iT3HJdbVBlpHIZMu/LQ==,type:str]
    DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:y2HhDjySzAM6LlpdoG9RE7/dURmUntGjeHH+L4LE2DhjZE4BjOy+sUpnuvgSIiJSBCYZuC4qUJk=,iv:4grKYGhvUfseRQuHZsPSlgeTggSx6XF/zkWrHy2hSpw=,tag:f4RuRTHIL5zzTt+u/w9Lag==,type:str]
    DRONE_GITEA_SERVER: ENC[AES256_GCM,data:Zab+4jhyGwUuHpCFp97EBlg8JQ57QzLt,iv:cWMDnvN6RFUxm3ZzeLAlNtmA3/MLFNrsNN+ESr62424=,tag:QbrBknQizMcv08vTRWtaUg==,type:str]
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:BE2vfwKHCnEpHQJm+6bRGr/hr6Aj8h430In4V8JuAZ0=,iv:zNSm5u4eqczzHQRPNSLTJB6kvPBEklehi+N7OT1SsEg=,tag:2N7Jkiur1ExRcNZeaPKyIw==,type:str]
    DRONE_SERVER_HOST: ENC[AES256_GCM,data:IZ/rwqnQlJPsHoHMrjZJSA==,iv:doIBmBGFBzbsbBUczzhIRN+mFLDEtGWQXXDAm8Y7Vic=,tag:xjrsyvG8jw6R54wTaP8pDA==,type:str]
    DRONE_SERVER_PROTO: ENC[AES256_GCM,data:OWs0cRA=,iv:4J5fJEjTxHRo7s+JQgZEET0BGhOqHilIIaAqWUr01Ww=,tag:1gs/qafsYrvnKtO1YCeatQ==,type:str]
    DRONE_DATABASE_DRIVER: ENC[AES256_GCM,data:18YdanOSEdE=,iv:6MKbIYZUbvvy/FkzKf2P9Go7LCBlurHWj1UUgOnF77U=,tag:1mjucG0AGuRwWpPWd6BLOw==,type:str]
    DRONE_DATABASE_DATASOURCE: ENC[AES256_GCM,data:8ktmadntbJSAAqCAJ8kJkB75fMPCC+flHZZ+C2kXod6YUyUeNPHQ1o6CJmGNXTKoW7+ihg8IK3DuWuf2A6qLZBHus5t/ijYETX3MLlIB8hS2halCpbHSLUWm,iv:gsMrilUzhyinJ4Wru3xwk6PwgbP3YmIdh+BisrDrWBs=,tag:xINwe8rqdHNelGKmqZ31dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMWZVTndhOVd3VVpNeWxn
            cFlFeWx0VTJxbXZ1Zzc1SUs0dGxiZ2lwUnk4Ci9zVGw0VUFTRVN2cm9KV1U4eXl2
            VHVMbjNrREVma3pZbEJKcDZCbXJGVG8KLS0tIEZzaS9HWHc5QnVhL3ppM1hZY1hh
            NHNnRE1SYkFxUGRLeXBCOXVMUmVCOWsKgkyXhLHFgnKjRsCPcc2L82QOLYb1TnYB
            zZkttb/WKcM5aLj/Vfwb4vjeGhwNxTXnxjc8CoJbid8SBRDmtXD+lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:TYfiaWQt/bH05IbtDfDq3GJiilvdrleSIIzRlUJ929P4HWT0HWDFHWiWjyS14tWHpYQyFRdRftdkfY2fFFrYySJhsdda59PYsI+V9PfHtWTUO0XGeAjFfKBlQAh9hmKeXU6iq7SYta7GvYPnkPgSF3rY4pSZ7PYxSB3SacnxrPw=,iv:sN8uIJf1uO+nopUk7C0RpWkO/pVWNWTVS9qfceZvwBA=,tag:qkAqazhlfM7AKf1lSQRGBg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
