apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-registry
  namespace: dev-tools
  labels:
    purpose: registry
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
