apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: dev-tools
  labels:
    purpose: git
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: git
  template:
    metadata:
      labels:
        purpose: git
    spec:
      volumes:
      - name: data-gitea
        persistentVolumeClaim:
          claimName: data-gitea
      - name: gitea-secret
        secret:
          secretName: gitea-secret
      - name: ssl-root
        secret:
          secretName: tls-ca
      initContainers:
      - name: fix-permissions
        image: registry.dev-tools.svc.cluster.local:5000/busybox:1.37.0
        command: ['sh', '-c']
        args: 
        - |
          mkdir -p /data/gitea
          mkdir -p /data/git
          chown -R 1000:1000 /data/gitea
          chmod -R 755 /data/gitea
          chmod -R 755 /data/git
      containers:
        - name: gitea
          image: gitea/gitea:1.23.7
          env:
          - name: USER_UID
            value: "1000"
          - name: USER_GID
            value: "1000"
          - name: GITEA__database__DB_TYPE
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: DB_TYPE
          - name: GITEA__database__HOST
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: HOST
          - name: GITEA__database__NAME
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: NAME
          - name: GITEA__database__USER
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: USER
          - name: GITEA__database__PASSWD
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: PASSWD
          - name: GITEA__database__SSL_MODE
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: SSL_MODE
          - name: GITEA__server__DOMAIN
            valueFrom:
              secretKeyRef:
                key: DOMAIN
                name: gitea-secret
          - name: GITEA__server__SSH_DOMAIN
            valueFrom:
              secretKeyRef:
                key: SSH_DOMAIN
                name: gitea-secret
          - name: GITEA__server__ROOT_URL
            valueFrom:
              secretKeyRef:
                key: ROOT_URL
                name: gitea-secret
          - name: GITEA__webhook__ALLOWED_HOST_LIST
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: ALLOWED_HOST_LIST
          - name: GITEA__security__INSTALL_LOCK
            value: "true"
          ports:
          - name: ssh
            containerPort: 22
          - name: http
            containerPort: 3000
          volumeMounts:
          - name: data-gitea
            mountPath: /data
          - name: gitea-secret
            mountPath: /data/gitea/conf/app.ini
            subPath: app.ini
          - name: tls-ca
            mountPath: /etc/ssl/certs/ca.crt
            subPath: ca.crt
