apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: dev-tools
  labels:
    purpose: git
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: git
  template:
    metadata:
      labels:
        purpose: git
    spec:
      volumes:
        - name: data-gitea
          persistentVolumeClaim:
            claimName: data-gitea
      initContainers:
        - name: fix-permissions
          image: registry.jbernh.xyz/busybox:1.37.0
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /data/gitea
              mkdir -p /data/git
              chown -R 1000:1000 /data/gitea
              chmod -R 755 /data/gitea
              chmod -R 755 /data/git
      containers:
        - name: gitea
          image: gitea/gitea:1.23.7
          envFrom:
            - configMapRef:
                name: gitea-config
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA__database__HOST
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: HOST
            - name: GITEA__database__NAME
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: NAME
            - name: GITEA__database__USER
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: USER
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: PASSWD
            - name: GITEA__webhook__ALLOWED_HOST_LIST
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: ALLOWED_HOST_LIST
            - name: GITEA__security__INSTALL_LOCK
              value: "true"
          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data-gitea
              mountPath: /data
