apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
    namespace: dev-tools
    labels:
        purpose: git
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:rEb2FS45bVc=,iv:xxVJzACkmqUGEnU2Vr/+VmGU8v2pXHtRU4nUpj4EPSo=,tag:xKi4lfJ+30Y6Slcv+uOygQ==,type:str]
    HOST: ENC[AES256_GCM,data:+TURH/6pNC5q7AgP5ybxCTsHuIqIgD1XBMZ5pn3lDsX4QJA=,iv:rj49SvswM3DW4m1whhrpzSrwwsLR0BbIyP+X0bushck=,tag:mAYofVXE8L+m247vEk+ZNg==,type:str]
    NAME: ENC[AES256_GCM,data:f8Bw3eg=,iv:+9tbrgALL/q+2F4QHpjBwrX1Uuha90/T8EbJrXt46Uo=,tag:WizHEwh+rlusGKLIRDN/nA==,type:str]
    USER: ENC[AES256_GCM,data:MRUH4yQ=,iv:FUPTqrWop81XZFnJ4Tr3zR2Oo9vWs+9SZeNYlnfQNvM=,tag:JaHSJS13FNywC5M8Mtd5Uw==,type:str]
    PASSWD: ENC[AES256_GCM,data:MhM9/AyUoxQ=,iv:JbLYHMNtUqe726yDURySecN3HPPbSUQgaN/VrHr0paQ=,tag:MQ9ctbKMxKI1q4Modx1LRA==,type:str]
    SSL_MODE: ENC[AES256_GCM,data:5DjoLrQ75A==,iv:i1Yc+lvxpqjb3EoIyIFWSup3RiAITCykC9ZUz9JYZfs=,tag:gMhdN9q0e3frj/vI48AJTg==,type:str]
    DOMAIN: ENC[AES256_GCM,data:jEqGQNFqqaDmcTg=,iv:NcdvPmk/jyn0s/1aETvcp4/uh5zl36EGMEFYb54rVn8=,tag:p5294qw8dtEPUv4HYhaXTg==,type:str]
    SSH_DOMAIN: ENC[AES256_GCM,data:4DluTrAgCiDxBDc=,iv:Q/u1ZnhPtUWbNJrjFCI74iKs81dm5weY8ROmf16AM18=,tag:OzN35++m9xJIqUKmZqMqbQ==,type:str]
    ROOT_URL: ENC[AES256_GCM,data:OGpQnmYO4W95+yk=,iv:8o+K3FI6V8X5g43qcvM962oTS6DT3QKMNncXKOosEI0=,tag:V3Ab566Px9gPv/m8Yq8q3A==,type:str]
    ALLOWED_HOST_LIST: ENC[AES256_GCM,data:KJGtua1eej1g/K5gsS5ll8ApuIGu4kQQWU++DhU=,iv:9QT2xEHaEXbuMAklNCXPhYni9G6aIWi/JZs83H5Qkco=,tag:W2mRzK/Gu7Kdv3h88ElSYw==,type:str]
sops:
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ2hYNmk5NDlwNThTRnNP
            NmhoNDQ4aEVZdytuSDBxczQvZEdUektFNEVBCmU3cndpUktNLzFneW5Ic0dTdGRV
            ZTRIWVZhbU9sYWVHZ0VOL3BLWWtQcE0KLS0tIFhLeVJkNjYvelkxYm9MRFNZS2cz
            WncvWFRrUzNjQ2ROS3hxNURPK3owSVUKpK9coRQSsHiZZqtBKIyM2GJiK3oBPeuD
            aUS1rOWoa4Idh4XxLlpC0EeDXt5fOuBGvQLTgUZImHM+9VTawlyhLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T05:16:33Z"
    mac: ENC[AES256_GCM,data:i/NQx59cmRBUrXtFm+JdjmPC3xdufa7F6VyDQ+VngHerJ8ATIjzNWEnRnCSVj65qq+4wovZ+iDeyaTFIaDCXMVFqYfQuzVIBJX2CaJiPm0cNV4b/7ErYwAGO8uha2urtFSDoEABzCYsVty6JRSwvXyhp69m+0I6mItF2WQeeVM8=,iv:UBvpvBTFz1H/yUMdLyx+n79ZaZ65CrF6NK5GaQm2YOU=,tag:KAiHb01D4UTECtvaARNHkQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
