apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secret
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: monitoring-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: monitoring/prometheus
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: monitoring/prometheus
        property: admin-password
