apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: brevo-secret
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: brevo-secret
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: monitoring/brevo
        metadataPolicy: None
        property: api_key
      secretKey: api_key
