apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secret
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: monitoring-secret
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: monitoring/prometheus
        metadataPolicy: None
        property: admin-user
      secretKey: admin-user
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: monitoring/prometheus
        metadataPolicy: None
        property: admin-password
      secretKey: admin-password
