apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea
  namespace: dev-tools
  labels:
    purpose: gitea
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
