apiVersion: v1
kind: Pod
metadata:
  name: helper
  namespace: dev-tools
spec:
  containers:
  - name: helper
    image: registry.dev-tools.svc.cluster.local:5000/helper:4
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command:
    - tail
    - -f
    - /dev/null
    tty: true
