services:
  app:
    environment:
      - POSTGRES_ADDR=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=mana
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=mana
      - SSL_MODE=disable
    build: .
    ports:
      - "4040:4040"
    depends_on:
      db:
        condition: service_healthy
  db:
    environment:
      - POSTGRES_USER=mana
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=mana
    image: "localhost/postgres:17"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
