# https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-internal
  namespace: dev-tools
spec:
  secretName: tls-internal
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - Cathedral
  dnsNames:
    - "*.svc.cluster.local"
    - "*.dev-tools.svc.cluster.local"
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
