apiVersion: batch/v1
kind: Job
metadata:
  name: init-table
  namespace: app
spec:
  template:
    spec:
      containers:
      - name: init-store
        image: postgres:16
        command: ["sh",  "-c", "psql -h db.app.svc.cluster.local -U $PGUSER -d $PGDB -c \"CREATE TABLE $MANA_TABLE(id SERIAL PRIMARY KEY, key varchar(100), value varchar(100) );\""]
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
          - name: PGDB
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_DB
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
          - name: MANA_TABLE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MANA_TABLE
      restartPolicy: OnFailure
  backoffLimit: 4
