apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:SkAZNCSGYEM=,iv:UM1F+EpcXKu8HNBnM3Q2f+d5WRrSGiZp2Jitx6zl5sw=,tag:X5XgSKkOAX/0HM2U1KooGQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Fh2A0w==,iv:reR+VORvLXPKlG8KGSak3oYOs+vRa8d0Tqv9dVbOVWM=,tag:3xmYxmt/2foCH8RTCLfkTg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Kr1HAufWCA==,iv:4m1Kqo1g0VAT2VHQ55ZCJTFJM0xrHA0r7mpRPCaV47E=,tag:Q8iXyilBB//LNgTPb8/9Ng==,type:str]
    MANA_TABLE: ENC[AES256_GCM,data:2GPq944dVA==,iv:+R67490r/DDITt1eV2Wyp0pMeEQzTWHqhglDkGTJm5U=,tag:KSAxcTIlNU/v9KFktVc93Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDR4YW12T2lDWFAwMVZw
            MHN0UjRoWkhtSzMzZExVdGQ0Y3paR3lzTlF3ClJneWNUaVZtYWx6Q0JMZ1pTN1Fh
            WkNtbUZvT3ZuVE4ySmZmcHk4UktWelkKLS0tIFpxSHJnc2RpTC9CdW4zd0J5RHJy
            SWtZMXJaR2JYbHVySmduTE9WUGswU3MKwmpFaFyD/O764GjNJLbRxS7nLqcwLZw2
            TWfPzrwwdnykm7oN8gA4sg6aIXBPkxZQDZjsWGI+Na8+bHEbNE9Afg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T05:31:02Z"
    mac: ENC[AES256_GCM,data:bAtfMeiVRu53zuB+RY2yboLuAoK/gTQY3CNdDiK2gwD1Wilo2TsvFYufPK66G7+V8IjJKPo8W4oiOEDbKXBBNDnO6Y77CQg9Yi1FrLfAcmD9O2WeNO7ocIXCxbdv1ZnkRbZEcXvKS7MFICTv5FJBfXYtBO7nR7tnim1zk+hpoJY=,iv:eEbcnhbH1wZ6MeWYP7I50cyzh3V6QXfRYLU+Aa7bonE=,tag:X7Q4GxyofY4HXxiuIJ6psg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
