apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ubbxbqDgH+s=,iv:pKoIncKFHmu1KGFE5TpC4jiwXFuoLixmhGgj1Unp/68=,tag:dZLNsHw53KPuWlJyJSD2Vw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:U3fFCA==,iv:YYiAq8POPQLhLqv2DvjcoChE26rnJb3CUxiOz9ZxjZk=,tag:6WxcWJ62FuALPKujSFzGEA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Ei9OhjnO0w==,iv:6mclUPLhVnKyElu3fTbEGh0MZt6gm7GZWiJO82twTUE=,tag:GvcZs75ePI6Ka9Csyc5+IA==,type:str]
    MANA_TABLE: ENC[AES256_GCM,data:i1H6M+tpxA==,iv:RoiERPV83+/u5dcfX/RoqRAYwz4PFfTM5fU4IRBqgn4=,tag:alOE/2DVikBqIkL4bqIong==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ1BQRGxKZzNyUzduRTY5
            QnRYU0ZweG9IN1pQTW1XRENsOFhzdmE3VlM0CkM4RDltaGc2TFloUHNxMjRyZURD
            d3hmUldOZ3NxNlJrMG5ZMW4wNXppT0kKLS0tIDZ6UTJkZGJBMUpSQjJvTDdNb2U0
            VE84ZmNnd1JqQW16UUQ4UGdQeW5ERXcK5mdgtmiS71r2XaNJygj9dmOsa7GOEcB0
            QVIOMu8OwL6Dz3e0aAOv6+M4eQe6YSALe/VRj7SzX0ZHu6fiXLbPJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T01:05:26Z"
    mac: ENC[AES256_GCM,data:YkHnzyzHJLs0OmP0+JsZ0fBWXoQw6b7OmeTkYlBTjMnnB+e1q7lgVTq0sFjLDwD0lhbMaJoRPVHertdEQAUO6I3zJWuMxa4OckQI1NX/gBo420r1O1kfumbPNtGXcjk+CoaDq1YExfd+Cq24aHvC79yvu/NKdeKp/+bVntRJPNo=,iv:bJoOhIac8NF3Kh3y13iQPbSZw2HTUJZE8yp6KPsXYHY=,tag:RSRKcseXDfxKfBxhxTjURA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
