apiVersion: v1
kind: Secret
metadata:
    name: secret-db-mana
    namespace: dev-tools
    labels:
        purpose: mana
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cc54K83VnYh53zwR,iv:Kt63oQYF/uwnjL1CUegVt3tXvieKgvZEWGqnNXTUgRc=,tag:DuBD1KAPXZoW2crUsRYAYg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:X5td/moMtvc=,iv:cKB8KPpfhsjOSpGNvEKgQqVPKfYAkVUil2HM1yT9rGQ=,tag:023Lg6zwiyGRh6Qw0gZ32Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWjdWMHdPVmswTm1oZ2dt
            WUI1NHlMcm1aSUFkTWhQOG82QU05aWl4QndzCkFCaW5pZEV0TjFuVncvK1d4Y2kr
            YXp5eWpjdUw1MWllK1BjZmxST0NWQkEKLS0tIHQ1RzBuSmp2OGRiTlo1akVDQWVw
            dnJzN2RVN21lb1R3Y0tmVUpkT1FJZUUKAaHpH/CGh11GBlo1GoiDUKEHBjt8ZM4v
            alz/aKag/wBVimWpMg9FD0Sc0NS4fKpwcw4A53OUNX4TxkUJbWSRkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T05:11:36Z"
    mac: ENC[AES256_GCM,data:JoIc8lfEuA/YEiruwKUo/HSYpeHzediaLnSot2w4ZCDTv5S3kQCDMRCeiSIYocu2IpbYMpR+mkX3XViMRdIgd8z6WsWDo8f2PZBHxdq02tFKXreLgcbLGf5PEcEZrK5P+MKdNejqjHAaFKLpiQVi14Ygqm9YL09QGBTHMNaDV1E=,iv:IlkHDndIi4JbR4u+xKTizpqwvgxbYPX9D17POFOi/+0=,tag:lkMSqM6ZyKXA+sfQ2wVAEw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
