apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OF2shKdGMpU=,iv:l5Lk1+nCodSaH9unN3twmkkyFYo1B6+zRq937PsQ6a4=,tag:Si5ruSuUiaKLwwAu+YTuPg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:YSgsjQ==,iv:JZPqjawgPyMh4DKjJf3EzNN9+bVbdMtu6gadpUJvTX8=,tag:2MmARMXBvfAVfnZIvv1Abw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:q6Rf+NdTUw==,iv:1PLMTxdJHmZHDKgQ6n9L5Kii8GslCoI1NnK52QulOlo=,tag:jVugqroU7uC9W72V0G+cVw==,type:str]
    MANA_TABLE: ENC[AES256_GCM,data:sZv4oVpYfw==,iv:YPwsLgkPN+D3bD4FllLMNnzBC+MmQUcVYDxKqcevtfc=,tag:Mqwr4nawQkWdquoDm2roFw==,type:str]
sops:
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MUY5MXVQOHh6WTc0Sngr
            c1ZqMHVrc2t0aysydkRIaUNTTFQzdk9jNVVjCmZaRDFZNzhISzlhQSt1S1NWQUlt
            OHZobkxTU0dxRktyQW5PdnRIK0FCNmcKLS0tIER4dzFza2xaaWxON2JrbjlvUHpa
            aXA3NGRnTWZSQ3htRkFVbjFLTjB3MjgKMCqq0BFmGygl6Jfl/fpGmHtRJrYOlg1g
            6n0bt5HoIEnJpYkd/tOIlRKn827cShz/OxZO0WQLka8enSfSWLBVxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T05:16:33Z"
    mac: ENC[AES256_GCM,data:YSxQCqQJLVHgHqpzgMOEsn5yXW+sIBkvEC7BgRzD5nKFS8AWB+zHBHkhZUrZbCcPwatEqAMVRIxV7Hw8Z3I2LDkIp5TnYAIpNKHXdNgu3iVUBxF4Ne5JNy2PoFwsAUyKsilhuU3GxWyqxFkxIz3eLctvTNM0hu1cKgXYnCe9H0w=,iv:BEuLPD75lj2q6WPRTeJQ2f9yWMdpy4QFcdZ5ClQ7XCE=,tag:OY2XExRACcvOrTxEvPJ0/A==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
