apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8Yjp70PNC8A=,iv:g+9oTlsHIgRrCk3ALHNEFF2ChqtDja6iVN80ArfLFAA=,tag:CBEbbYp3UAoaNoDMHvCLJw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:v3DSeQ==,iv:1FFoaeokXBO44EV59QVmA/MsBAxBu6Yg02/zpO+qKpg=,tag:isWaEVM7xes7+9q2UTAT9A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:cUSGx0b15Q==,iv:82dMh6qsAR5yLAqFufoIXritsEdzGI0fnOtAQx4As8I=,tag:9YnawvOIm1AhA+iv98DkPg==,type:str]
    MANA_TABLE: ENC[AES256_GCM,data:aay4/mH4ZQ==,iv:nIoFvDw53jb3E3ru0skp/srCXYpAB1vvsj1XichfWrM=,tag:41x+tVNAsXCIJJ0ZtKSEIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaHJCNEZJNkdnZW5VcDJ6
            TWdyN2NsZ2xSaVNBNy9iRFc2K2JJMjUwZmk4CkhmeHlmbG1KV1hzclcxcTBoSVJV
            Y3JJU2xRN0xCMUMyRzQzV3pmd000dGMKLS0tIC91SzFhMXhRTnNMRHFrRy9ERkVu
            ZjV2bVNsTnhGbGFVdGZWWnVqK3J4VzAKsL1Jf0crzWu5nFZTCd3mXVa0lBgOrL88
            lfQZuvwcYlsHlYnvT2EdxZiSGlGmbU9sLn4ZynftFY5rj48kvKA0mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-01T18:44:29Z"
    mac: ENC[AES256_GCM,data:DSBJ07oU3Y7hlMFRdaODC35ZISaKat5F/WiKaG1nugrdUtLLHu0zakS9ScrFJSyOEyiBk7nzouuMnWH4d+8Ciydjrg2JoP0otJZPlVag4tBR1hyhH9rzYaIBQIetlg9c2KTrSfD3MA8coLrCZAkiy4k4GpVMb2AxR62+bFefJtM=,iv:DJBka0Sjsr1grgF1+uJ9SSxbrTos/L10aRiCfROTfzQ=,tag:9drLcHTb86aljciZsZKLRQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.9.4
