apiVersion: v1
kind: Secret
metadata:
    name: secret-db-mana
    namespace: app
    labels:
        purpose: mana
        database: postgresql
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JyRROHtHi+ETwhHB,iv:Qa2drrJufZ0WZsutCVMQss+6JBFGy9elTxo+JoHsReY=,tag:1hsbHDPEmqS8GjTMyG9t8g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7zk+ibCRK0w=,iv:be8JlljWlo3gLIWrwFEOj5sXlbGtClgg1bLJYoT/R+w=,tag:QPhRLUG/kUlTdgRzaZOv2A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:V2jAF6nWxmqJQ7PG,iv:XMEfJFxG/QT+rv37qsCL4nGx+jFdp50S1KBRSNqBkWA=,tag:SgnJrZGHOqvoWGRh73wj/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENVY4K3hnOVlrenRnT1VS
            YnlYSC9hRFRiVUxmalcwK2k2NFpHOGY5SEFvCjhUYVZySVhDMGJWN04yTUorMnA2
            N3JUTTNrSnNraU54Skh4RHlRZTdERHMKLS0tIC9FWXJzN2wvcHpOM3lsaUt2T0xI
            MDY1T1IzV0loQmpwWlh6dEtrdlc2bzQKY8DydW5d1ySkw10ajkOT0zsClp7ksQVo
            OzU/sW9tQ4kOhI1tAbf7fo/Y98/IjomiCzjKqS4vph9vkUMIWK9hdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T01:39:55Z"
    mac: ENC[AES256_GCM,data:iQOmnTwvoTegzMjUbgbPQCzETp/y1KLuLCyK964Ufk5wBZ7zP6PIcTFpmhhNe77teqBYlQ2wFlZVkWyQBKHICuHrJfQF2Zj4z0AhqKI4wiz8y76HFkgRwBKBdjAq+nOgcfEfxXQGPnptKCjUXtw1XKhPGalVo1MFF8Ojaid3ZoM=,iv:577oWUFgVcOJW1EvvFqaP4SDYv9W3qM8FvmM5B4DHPQ=,tag:TsmpL/nC5vybpyEGIlOXuA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
