apiVersion: v1
kind: Secret
metadata:
    name: secret-db-mana
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hlW/WfeFg28ULt2a,iv:wtkokhFOCJIfNk8GDoq3DtsnWkO647weeCQOeWh6ibU=,tag:iiSekxFbE9HwXisunCZNYA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:zg/6HoqVRqE=,iv:TjIh6shvc87qV1lmFdYs+8HDbYawRwG4ai3Yt5T4k+s=,tag:2hkf9x8XxKknW1bLe9w+YQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:FOjTYtmDgfjpZPBl,iv:QDw4flV2fGBbKZNw15IEO4I4fqbD4mjJ8I8/GGfKqvw=,tag:YC77HUpdGoFV8qWOFhf8FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d2pKM2FsbmVTcmNwV2FJ
            U0xFcml0SmlDWlpzOWNYbXViQ21YT3M2cFhRClgzNVkrWHgxa1YyNXVSZGFKT3J1
            U1VHb3pIbGZxT28yNzBoanduMXZMVUUKLS0tIDRYcHRmaThQOCtldlhKdHhxRzVm
            TmY0bjZKL1dmRmVCWURlS1lqWGVCNHMKh+dDrFAdsH6ZMR8/5mKGYU4Lp8u5PYd2
            twJAb42yvKkssASTXj5V1DduJIoKfRhyP1VN60kg8s78vE6AKJ5vVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T03:42:22Z"
    mac: ENC[AES256_GCM,data:hS3bddZAcFpurOtX1RUQuz8PboNAnpVritEs1ng8jnibEvZ+vXLcybqqBzyyuk/zrLZQGEv9tkuQH7IZUjvDMFKSb3lHZpt6UVZ2XQYwexQO8nkoRAdRIGJdVmECx/4YPq4wM3i2OStoWw1aAij5kdIu8svvq+FHDcroyMh6clQ=,iv:4sl4MeAEsncMfKmaiZWyl8rJxoikeg4LaL5PG8EGMmo=,tag:wS4TdQE2OOj4bLRTb0UHOA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
