apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: app
    labels:
        purpose: data-mana
        database: postgresql
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4lJucDjfPk4=,iv:/UtVUGUHzolIT04nyqwcHbUdaJ78/Alb7Uqrc2Y915M=,tag:AdvzLh72kfuQDkbLoC3G7A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:rOLBXA==,iv:pGwhJU7UBXD1bYW/Easf+m8WStRsOVK4Xi1/Ala0uxQ=,tag:bt0HX555UFu0lhLHRUEtSA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:9jng+lOugg==,iv:6n0VOTwcdgeYzc65mvbgDNtFp4fF/TaMoMX9put71v4=,tag:FB55KxG5rkCLqzZ8oM2KKw==,type:str]
    MANA_TABLE: ENC[AES256_GCM,data:U44ImTLlhQ==,iv:NgYn/2mh+BhL6AZ6FhHf5CZC7PgGpzkEcxvd3tfq6SA=,tag:M/gBpLcgVOXqMDtNUclifA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hgs4ay6z3tfpj9fqkdt7l5rg4ggdyp6jlt6c90de43yknk6mvuqpp2cnr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMDIvMURGYmZweWZISFE1
            QUZqOWJwWXV2eTB0ZndNL1ZBTDN5TXRaSkJBClpzaXJSRjVoanNkZi9tV1lSM0dt
            N3lCKzJrcnAzZFo5QjhDZ0szcWN2YU0KLS0tIHVEbHYrQW1lK3o3WWVuN0E2MDh1
            N0grb1NzSmpmaXRWSkZSR1N6U2FPUmsKxC1d4l93y55WvnoT3h0Eny/i8DSjEwrU
            LVEXWAVo+E2CzG3DYftumX6bKviwwOca7X8YYNH2jgodRXN5TL6ZOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:09:52Z"
    mac: ENC[AES256_GCM,data:qELiFCvbrtiy0x6U5mbhBKSqIva6/rLR2NeIfUBMu4J5y3A7kNxOuLIMX9fhAvp37BO7sLnzOqf3m1XAM3fWcNz/4NvfC7cRBioYRj5qNtK9wFtRTb53xFgn8KeOIfe0zvrujnd+4fYqL1qwr6+c7J+OyoZP7bqNWQeOhU8D86Y=,iv:cWoua7fAFx6EYDNJY16BXkPwYbzQuJlDvsdA8li7lP8=,tag:5OfOc0AYSl1KjQU7WECoMw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.4
