apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app
spec:
  type: ClusterIP
  selector:
    purpose: data-mana
    database: postgresql
  ports:
    - port: 5432
      targetPort: 5432
