apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-tools
  labels:
    purpose: tools
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/opt/liquid/data-tools"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-worker-01
                - kube-worker-02
                - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-tools
  namespace: dev-tools
spec:
  selector:
    matchLabels:
      purpose: tools
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
